"""AI Opener Generator Routes (AI破冰文案路由)."""

from typing import Annotated, Any

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession

from xspider.admin.auth import get_current_active_user, get_db_session
from xspider.admin.models import AdminUser
from xspider.admin.services import CreditService, OpenerGenerator

router = APIRouter(prefix="/openers", tags=["AI Openers"])


@router.post("/generate")
async def generate_openers(
    target_screen_name: str,
    target_twitter_id: str,
    current_user: Annotated[AdminUser, Depends(get_current_active_user)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    lead_id: int | None = None,
    commenter_id: int | None = None,
    num_openers: int = Query(3, ge=1, le=5),
) -> dict[str, Any]:
    """Generate personalized opener messages for a target user."""
    # Check credits
    credit_service = CreditService(db)
    required_credits = OpenerGenerator.CREDITS_PER_GENERATION

    if not await credit_service.check_balance(current_user.id, required_credits):
        raise HTTPException(
            status_code=402,
            detail=f"Insufficient credits. Required: {required_credits}",
        )

    generator = OpenerGenerator(db)

    try:
        opener = await generator.generate_openers(
            user_id=current_user.id,
            target_screen_name=target_screen_name,
            target_twitter_id=target_twitter_id,
            lead_id=lead_id,
            commenter_id=commenter_id,
            num_openers=num_openers,
        )

        # Deduct credits
        await credit_service.deduct_credits(
            user_id=current_user.id,
            amount=required_credits,
            reason=f"Generated openers for @{target_screen_name}",
        )

        return {
            "success": True,
            "opener": {
                "id": opener.id,
                "target_screen_name": opener.target_screen_name,
                "openers": opener.openers,
                "user_bio": opener.user_bio,
                "user_interests": opener.user_interests,
                "model_used": opener.model_used,
                "tokens_used": opener.tokens_used,
                "credits_used": opener.credits_used,
                "created_at": opener.created_at.isoformat() if opener.created_at else None,
            },
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/")
async def get_user_openers(
    current_user: Annotated[AdminUser, Depends(get_current_active_user)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
) -> dict[str, Any]:
    """Get all openers generated by the current user."""
    generator = OpenerGenerator(db)
    openers, total = await generator.get_user_openers(
        user_id=current_user.id,
        page=page,
        page_size=page_size,
    )

    return {
        "openers": [
            {
                "id": o.id,
                "target_screen_name": o.target_screen_name,
                "openers": o.openers,
                "is_used": o.is_used,
                "used_at": o.used_at.isoformat() if o.used_at else None,
                "response_received": o.response_received,
                "created_at": o.created_at.isoformat() if o.created_at else None,
            }
            for o in openers
        ],
        "total": total,
        "page": page,
        "page_size": page_size,
    }


@router.put("/{opener_id}/used")
async def mark_opener_used(
    opener_id: int,
    current_user: Annotated[AdminUser, Depends(get_current_active_user)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    selected_index: int = 0,
) -> dict[str, Any]:
    """Mark an opener as used."""
    generator = OpenerGenerator(db)

    try:
        opener = await generator.mark_opener_used(
            opener_id=opener_id,
            user_id=current_user.id,
            selected_index=selected_index,
        )
        return {
            "success": True,
            "is_used": opener.is_used,
            "used_at": opener.used_at.isoformat() if opener.used_at else None,
        }
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.put("/{opener_id}/response")
async def mark_response_received(
    opener_id: int,
    current_user: Annotated[AdminUser, Depends(get_current_active_user)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> dict[str, Any]:
    """Mark that a response was received for an opener."""
    generator = OpenerGenerator(db)

    try:
        opener = await generator.mark_response_received(
            opener_id=opener_id,
            user_id=current_user.id,
        )
        return {"success": True, "response_received": opener.response_received}
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.get("/stats")
async def get_opener_stats(
    current_user: Annotated[AdminUser, Depends(get_current_active_user)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> dict[str, Any]:
    """Get opener generation statistics."""
    generator = OpenerGenerator(db)
    return await generator.get_opener_stats(current_user.id)
